// Mock data used for the static GitHub Pages demo build

export const DEMO_USERS = [
  {
    id: 'user-1',
    username: 'xeno_builds',
    name: 'Xeno',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=80&h=80&fit=crop',
    bio: 'RGB everything. RTX or bust.',
    avgRating: 8.7,
    totalPosts: 3,
    totalRatings: 42,
    _count: { posts: 3, followers: 128, following: 44 },
  },
  {
    id: 'user-2',
    username: 'minimalist_dev',
    name: 'Sara K.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    bio: 'Clean desk, clean code.',
    avgRating: 9.1,
    totalPosts: 2,
    totalRatings: 31,
    _count: { posts: 2, followers: 204, following: 17 },
  },
  {
    id: 'user-3',
    username: 'rgb_overlord',
    name: 'Daan V.',
    avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=80&h=80&fit=crop',
    bio: 'If it doesn\'t glow it doesn\'t go.',
    avgRating: 7.8,
    totalPosts: 2,
    totalRatings: 19,
    _count: { posts: 2, followers: 76, following: 55 },
  },
]

export const DEMO_POSTS = [
  {
    id: 'post-1',
    title: 'Ultrawide battlestation — RTX 4090 + dual arm setup',
    description: 'Finally finished the cable management after 3 weeks. The 49" Samsung Odyssey G9 is an absolute game-changer. Paired with a 4090 it handles everything I throw at it at max settings.\n\nThe custom loop took a weekend to build but temps are incredible — GPU never goes above 62°C under full load.',
    images: [
      'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593640408182-31c228dfd41f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&h=800&fit=crop',
    ],
    tags: ['gaming', 'ultrawide', 'custom-loop'],
    avgRating: 9.2,
    ratingCount: 18,
    commentCount: 7,
    buildCost: 6800,
    cpu: 'Intel Core i9-14900K',
    gpu: 'NVIDIA RTX 4090 FE',
    ram: '64GB DDR5-6000 G.Skill Trident Z5',
    storage: '2TB Samsung 990 Pro + 4TB WD Black',
    peripherals: 'Samsung Odyssey G9 49", Logitech G Pro X Superlight, Wooting 60HE',
    deskChair: 'UPLIFT V2 Standing Desk + Herman Miller Embody',
    published: true,
    featured: true,
    pinned: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[0],
  },
  {
    id: 'post-2',
    title: 'Minimal all-white dev setup — MacBook M3 Max + 5K display',
    description: 'Less is more. Switched from a full tower to this minimal setup 6 months ago and I\'ve never been more productive.\n\nThe Studio Display is worth every cent — the speakers alone beat my old dedicated setup. Cable management took 2 hours but now there\'s literally one visible cable.',
    images: [
      'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&h=800&fit=crop',
    ],
    tags: ['minimal', 'mac', 'workspace'],
    avgRating: 9.5,
    ratingCount: 24,
    commentCount: 12,
    buildCost: 5200,
    cpu: 'Apple M3 Max (16-core)',
    gpu: 'Integrated 40-core GPU',
    ram: '128GB Unified Memory',
    storage: '2TB SSD (internal)',
    peripherals: 'Apple Studio Display 5K, Apple Magic Keyboard, Logitech MX Master 3S',
    deskChair: 'IKEA ALEX desk + Secretlab TITAN Evo',
    published: true,
    featured: true,
    pinned: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[1],
  },
  {
    id: 'post-3',
    title: 'RGB chaos build — full Lian Li O11D with custom cables',
    description: 'Yes, every single cable is custom sleeved. Yes, it took 3 weeks. No, I don\'t regret it.\n\nThe Lian Li O11 Dynamic is the perfect case for a full distro plate loop. Coolant is EKWB UV blue — it glows like crazy under the UV strip.',
    images: [
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=800&fit=crop',
    ],
    tags: ['gaming', 'rgb', 'custom-loop', 'modding'],
    avgRating: 8.1,
    ratingCount: 11,
    commentCount: 9,
    buildCost: 4200,
    cpu: 'AMD Ryzen 9 7950X',
    gpu: 'AMD RX 7900 XTX (watercooled)',
    ram: '64GB DDR5-6000 Corsair Dominator',
    storage: '2TB WD Black SN850X',
    peripherals: 'LG 27GP950-B x2, Razer Huntsman V2, Razer Viper V2 Pro',
    deskChair: 'Custom built desk + DXRacer Master',
    published: true,
    featured: false,
    pinned: false,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[2],
  },
  {
    id: 'post-4',
    title: 'Home office meets gaming rig — WFH done right',
    description: 'Work from home since 2021 and finally invested in a proper setup. The key was dual-purposing everything — the monitors work for both coding and gaming, the keyboard has a work profile and a gaming profile.',
    images: [
      'https://images.unsplash.com/photo-1593640408182-31c228dfd41f?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=1200&h=800&fit=crop',
    ],
    tags: ['workspace', 'wfh', 'dual-purpose'],
    avgRating: 7.6,
    ratingCount: 8,
    commentCount: 4,
    buildCost: 3100,
    cpu: 'Intel Core i7-13700K',
    gpu: 'NVIDIA RTX 4070 Ti',
    ram: '32GB DDR5-5600',
    storage: '1TB Samsung 980 Pro',
    peripherals: 'Dell U2723D x2, Keychron Q1 Pro, Logitech G502 X Plus',
    deskChair: 'Flexispot E7 Pro + Haworth Fern',
    published: true,
    featured: false,
    pinned: false,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[0],
  },
  {
    id: 'post-5',
    title: 'Budget god — $800 setup that outperforms $3k rigs',
    description: 'Proof that you don\'t need to spend a fortune. This entire setup was built for under $800 including the monitor, and it runs everything I need at 1440p 144Hz smoothly.\n\nBought the GPU during a sale, CPU is previous gen, monitor was refurbished. Smart shopping beats blind spending.',
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&h=800&fit=crop',
    ],
    tags: ['budget', 'gaming', '1440p'],
    avgRating: 8.4,
    ratingCount: 15,
    commentCount: 21,
    buildCost: 800,
    cpu: 'AMD Ryzen 5 5600',
    gpu: 'AMD RX 6700 XT',
    ram: '16GB DDR4-3600',
    storage: '1TB SK Hynix P41',
    peripherals: 'LG 27GP850-B 1440p 165Hz, Akko 3068B, Logitech G305',
    deskChair: 'IKEA LINNMON + MARKUS',
    published: true,
    featured: false,
    pinned: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[1],
  },
  {
    id: 'post-6',
    title: 'Dark academia aesthetic desk — vintage meets tech',
    description: 'Went for a dark academia aesthetic — warm wood tones, leather, brass accents, but with modern tech hidden underneath. The monitor arm hides all cables behind the desk riser.',
    images: [
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=1200&h=800&fit=crop',
    ],
    tags: ['aesthetic', 'minimal', 'workspace'],
    avgRating: 9.0,
    ratingCount: 13,
    commentCount: 6,
    buildCost: 2400,
    cpu: 'Apple M2 Pro',
    gpu: 'Integrated 19-core GPU',
    ram: '32GB Unified Memory',
    storage: '1TB SSD',
    peripherals: 'LG UltraFine 4K 27", Keychron Q5 (brass knob), Apple Magic Trackpad',
    deskChair: 'Vintage wooden desk + leather office chair',
    published: true,
    featured: false,
    pinned: false,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[2],
  },
]

export const DEMO_COMMENTS = [
  {
    id: 'comment-1',
    body: 'Cable management is insane! How long did that take you?',
    postId: 'post-1',
    parentId: null,
    deleted: false,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    author: DEMO_USERS[1],
    replies: [
      {
        id: 'comment-2',
        body: 'About 3 days total. Worth it though 😅',
        postId: 'post-1',
        parentId: 'comment-1',
        deleted: false,
        createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
        author: DEMO_USERS[0],
        replies: [],
      },
    ],
  },
  {
    id: 'comment-3',
    body: 'What temps are you getting on the 4090 under load?',
    postId: 'post-1',
    parentId: null,
    deleted: false,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    author: DEMO_USERS[2],
    replies: [],
  },
]
